[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day0"
path = "src/day0/main.rs"

[[bin]]
name = "day1"
path = "src/day1/main.rs"

[[bin]]
name = "day2"
path = "src/day2/main.rs"

[[bin]]
name = "day3"
path = "src/day3/main.rs"
